(attr_dashes) @constant
(attr_key) @constructor
(attr_separator) @constant
(attr_value) @module
(dashes) @type
(headline) @keyword
(list_dash) @number
(list_section_token) @number
(nb_whitespace) @whitespace.test
(not_a_checkmark) @string
(p_section_token) @number
(paragraph_first_word) @keyword
(title_section_token) @number
(todo_checkmark) @property
(todo_left_bracket) @function
(todo_right_bracket) @function
(todo_section_token) @number
(word) @tag
