(dashes) @type
(headline) @keyword
(list_dash) @number
(list_section_token) @number
(p_section_token) @number
(paragraph_first_word) @keyword
(title_section_token) @number
(todo_section_token) @number
(whitespace) @whitespace.test
(word) @tag
(todo_left_bracket) @function
(todo_right_bracket) @function
(todo_checkmark) @property
(not_a_checkmark) @string
