(attr_bool) @neo_attr_bool
(attr_dashes) @neo_attr_dashes
(attr_key) @neo_attr_key
(attr_separator) @neo_attr_separator
(attr_value) @neo_attr_value
(code_token) @neo_section_token
(container_token) @neo_section_start_end_token
(html_token) @neo_section_token
(list_dash) @neo_list_dash
(list_token) @neo_section_token
(nb_whitespace) @neo_nb_whitespace
(not_a_checkmark) @neo_checkbox_in_progress
(p_token) @neo_section_token
(paragraph_first_word) @neo_paragraph_first_word
(section_dashes) @neo_section_dashes
(title_token) @neo_section_token
(todo_checkmark) @neo_checkbox_checkmark
(todo_left_bracket) @neo_checkbox_bracket
(todo_right_bracket) @neo_checkbox_bracket
(todo_token) @neo_section_token
(word) @neo_paragraph_nth_word
