#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 1
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  aux_sym_attr_bool_token1 = 1,
  sym_attr_dashes = 2,
  sym_attr_separator = 3,
  sym_attr_value = 4,
  sym_code_section_token = 5,
  sym_html_section_token = 6,
  sym_list_dash = 7,
  sym_list_section_token = 8,
  anon_sym_LT = 9,
  sym_following_word_chars = 10,
  sym_nb_whitespace = 11,
  sym_newline = 12,
  sym_non_lt_char = 13,
  sym_p_section_token = 14,
  sym_section_dashes = 15,
  sym_section_start_end_token = 16,
  sym_title_section_token = 17,
  sym_todo_left_bracket = 18,
  sym_todo_right_bracket = 19,
  sym_todo_checkmark = 20,
  sym_not_a_checkmark = 21,
  sym_todo_section_token = 22,
  sym_code_body = 23,
  sym_html_body = 24,
  sym_source_file = 25,
  sym__attr = 26,
  sym_attr_kv_pair = 27,
  sym_attr_bool = 28,
  sym_attr_key = 29,
  sym_code_end_section = 30,
  sym_code_start_section = 31,
  sym_headline = 32,
  sym_html_end_section = 33,
  sym_html_start_section = 34,
  sym_initial_word_chars = 35,
  sym_list_item = 36,
  sym_list_section = 37,
  sym_lt_with_non_lt_char = 38,
  sym_p_section = 39,
  sym_paragraph = 40,
  sym_paragraph_body = 41,
  sym_paragraph_first_word = 42,
  sym_title_section = 43,
  sym_empty_todo_bracket = 44,
  sym_completed_todo_bracket = 45,
  sym_in_progress_todo_bracket = 46,
  sym_todo_item = 47,
  sym_todo_section = 48,
  sym_word = 49,
  sym__wordbreak = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_code_end_section_repeat1 = 52,
  aux_sym_list_section_repeat1 = 53,
  aux_sym_list_section_repeat2 = 54,
  aux_sym_paragraph_repeat1 = 55,
  aux_sym_todo_item_repeat1 = 56,
  aux_sym_todo_section_repeat1 = 57,
  anon_alias_sym_headline = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_attr_bool_token1] = "attr_bool_token1",
  [sym_attr_dashes] = "attr_dashes",
  [sym_attr_separator] = "attr_separator",
  [sym_attr_value] = "attr_value",
  [sym_code_section_token] = "code_section_token",
  [sym_html_section_token] = "html_section_token",
  [sym_list_dash] = "list_dash",
  [sym_list_section_token] = "list_section_token",
  [anon_sym_LT] = "<",
  [sym_following_word_chars] = "following_word_chars",
  [sym_nb_whitespace] = "nb_whitespace",
  [sym_newline] = "newline",
  [sym_non_lt_char] = "non_lt_char",
  [sym_p_section_token] = "p_section_token",
  [sym_section_dashes] = "section_dashes",
  [sym_section_start_end_token] = "section_start_end_token",
  [sym_title_section_token] = "title_section_token",
  [sym_todo_left_bracket] = "todo_left_bracket",
  [sym_todo_right_bracket] = "todo_right_bracket",
  [sym_todo_checkmark] = "todo_checkmark",
  [sym_not_a_checkmark] = "not_a_checkmark",
  [sym_todo_section_token] = "todo_section_token",
  [sym_code_body] = "code_body",
  [sym_html_body] = "html_body",
  [sym_source_file] = "source_file",
  [sym__attr] = "_attr",
  [sym_attr_kv_pair] = "attr_kv_pair",
  [sym_attr_bool] = "attr_bool",
  [sym_attr_key] = "attr_key",
  [sym_code_end_section] = "code_end_section",
  [sym_code_start_section] = "code_start_section",
  [sym_headline] = "headline",
  [sym_html_end_section] = "html_end_section",
  [sym_html_start_section] = "html_start_section",
  [sym_initial_word_chars] = "initial_word_chars",
  [sym_list_item] = "list_item",
  [sym_list_section] = "list_section",
  [sym_lt_with_non_lt_char] = "lt_with_non_lt_char",
  [sym_p_section] = "p_section",
  [sym_paragraph] = "paragraph",
  [sym_paragraph_body] = "paragraph_body",
  [sym_paragraph_first_word] = "paragraph_first_word",
  [sym_title_section] = "title_section",
  [sym_empty_todo_bracket] = "empty_todo_bracket",
  [sym_completed_todo_bracket] = "completed_todo_bracket",
  [sym_in_progress_todo_bracket] = "in_progress_todo_bracket",
  [sym_todo_item] = "todo_item",
  [sym_todo_section] = "todo_section",
  [sym_word] = "word",
  [sym__wordbreak] = "_wordbreak",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_code_end_section_repeat1] = "code_end_section_repeat1",
  [aux_sym_list_section_repeat1] = "list_section_repeat1",
  [aux_sym_list_section_repeat2] = "list_section_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_todo_item_repeat1] = "todo_item_repeat1",
  [aux_sym_todo_section_repeat1] = "todo_section_repeat1",
  [anon_alias_sym_headline] = "headline",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_attr_bool_token1] = aux_sym_attr_bool_token1,
  [sym_attr_dashes] = sym_attr_dashes,
  [sym_attr_separator] = sym_attr_separator,
  [sym_attr_value] = sym_attr_value,
  [sym_code_section_token] = sym_code_section_token,
  [sym_html_section_token] = sym_html_section_token,
  [sym_list_dash] = sym_list_dash,
  [sym_list_section_token] = sym_list_section_token,
  [anon_sym_LT] = anon_sym_LT,
  [sym_following_word_chars] = sym_following_word_chars,
  [sym_nb_whitespace] = sym_nb_whitespace,
  [sym_newline] = sym_newline,
  [sym_non_lt_char] = sym_non_lt_char,
  [sym_p_section_token] = sym_p_section_token,
  [sym_section_dashes] = sym_section_dashes,
  [sym_section_start_end_token] = sym_section_start_end_token,
  [sym_title_section_token] = sym_title_section_token,
  [sym_todo_left_bracket] = sym_todo_left_bracket,
  [sym_todo_right_bracket] = sym_todo_right_bracket,
  [sym_todo_checkmark] = sym_todo_checkmark,
  [sym_not_a_checkmark] = sym_not_a_checkmark,
  [sym_todo_section_token] = sym_todo_section_token,
  [sym_code_body] = sym_code_body,
  [sym_html_body] = sym_html_body,
  [sym_source_file] = sym_source_file,
  [sym__attr] = sym__attr,
  [sym_attr_kv_pair] = sym_attr_kv_pair,
  [sym_attr_bool] = sym_attr_bool,
  [sym_attr_key] = sym_attr_key,
  [sym_code_end_section] = sym_code_end_section,
  [sym_code_start_section] = sym_code_start_section,
  [sym_headline] = sym_headline,
  [sym_html_end_section] = sym_html_end_section,
  [sym_html_start_section] = sym_html_start_section,
  [sym_initial_word_chars] = sym_initial_word_chars,
  [sym_list_item] = sym_list_item,
  [sym_list_section] = sym_list_section,
  [sym_lt_with_non_lt_char] = sym_lt_with_non_lt_char,
  [sym_p_section] = sym_p_section,
  [sym_paragraph] = sym_paragraph,
  [sym_paragraph_body] = sym_paragraph_body,
  [sym_paragraph_first_word] = sym_paragraph_first_word,
  [sym_title_section] = sym_title_section,
  [sym_empty_todo_bracket] = sym_empty_todo_bracket,
  [sym_completed_todo_bracket] = sym_completed_todo_bracket,
  [sym_in_progress_todo_bracket] = sym_in_progress_todo_bracket,
  [sym_todo_item] = sym_todo_item,
  [sym_todo_section] = sym_todo_section,
  [sym_word] = sym_word,
  [sym__wordbreak] = sym__wordbreak,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_code_end_section_repeat1] = aux_sym_code_end_section_repeat1,
  [aux_sym_list_section_repeat1] = aux_sym_list_section_repeat1,
  [aux_sym_list_section_repeat2] = aux_sym_list_section_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_todo_item_repeat1] = aux_sym_todo_item_repeat1,
  [aux_sym_todo_section_repeat1] = aux_sym_todo_section_repeat1,
  [anon_alias_sym_headline] = anon_alias_sym_headline,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_attr_bool_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_attr_dashes] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_value] = {
    .visible = true,
    .named = true,
  },
  [sym_code_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_html_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_list_dash] = {
    .visible = true,
    .named = true,
  },
  [sym_list_section_token] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_following_word_chars] = {
    .visible = true,
    .named = true,
  },
  [sym_nb_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_non_lt_char] = {
    .visible = true,
    .named = true,
  },
  [sym_p_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_section_dashes] = {
    .visible = true,
    .named = true,
  },
  [sym_section_start_end_token] = {
    .visible = true,
    .named = true,
  },
  [sym_title_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_left_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_right_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_checkmark] = {
    .visible = true,
    .named = true,
  },
  [sym_not_a_checkmark] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_code_body] = {
    .visible = true,
    .named = true,
  },
  [sym_html_body] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__attr] = {
    .visible = false,
    .named = true,
  },
  [sym_attr_kv_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_key] = {
    .visible = true,
    .named = true,
  },
  [sym_code_end_section] = {
    .visible = true,
    .named = true,
  },
  [sym_code_start_section] = {
    .visible = true,
    .named = true,
  },
  [sym_headline] = {
    .visible = true,
    .named = true,
  },
  [sym_html_end_section] = {
    .visible = true,
    .named = true,
  },
  [sym_html_start_section] = {
    .visible = true,
    .named = true,
  },
  [sym_initial_word_chars] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_list_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lt_with_non_lt_char] = {
    .visible = true,
    .named = true,
  },
  [sym_p_section] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_body] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_first_word] = {
    .visible = true,
    .named = true,
  },
  [sym_title_section] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_in_progress_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_item] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_section] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym__wordbreak] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_end_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_section_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_todo_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_todo_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_headline] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_headline,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_paragraph, 2,
    sym_paragraph,
    anon_alias_sym_headline,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      if (lookahead == '\t') ADVANCE(39);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == '-') ADVANCE(33);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ':') ADVANCE(29);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'p') ADVANCE(42);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(41);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ':') ADVANCE(29);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'h') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(43);
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(49);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(41);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_attr_bool_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attr_dashes);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attr_separator);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_attr_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_code_section_token);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_html_section_token);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_list_dash);
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_list_dash);
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_list_section_token);
      if (lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_following_word_chars);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_nb_whitespace);
      if (lookahead == '\t') ADVANCE(39);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_nb_whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_non_lt_char);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_non_lt_char);
      if (lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_p_section_token);
      if (lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_section_dashes);
      if (lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_section_start_end_token);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_title_section_token);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_todo_left_bracket);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_todo_right_bracket);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_todo_checkmark);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_not_a_checkmark);
      if (lookahead != 0 &&
          lookahead != 'X' &&
          lookahead != ']' &&
          lookahead != 'x') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_todo_section_token);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 25},
  [3] = {.lex_state = 25},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 25},
  [6] = {.lex_state = 25},
  [7] = {.lex_state = 25},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 25},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 24},
  [24] = {.lex_state = 24},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 24},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 24},
  [29] = {.lex_state = 24},
  [30] = {.lex_state = 24},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 25},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 25},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 24},
  [54] = {.lex_state = 25},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 25},
  [58] = {.lex_state = 25},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 22},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 25},
  [69] = {.lex_state = 25},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 25},
  [76] = {.lex_state = 25},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 24},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 21},
  [81] = {.lex_state = 21},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 25},
  [86] = {.lex_state = 25},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 3},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 21},
  [92] = {.lex_state = 25},
  [93] = {.lex_state = 21},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_attr_dashes] = ACTIONS(1),
    [sym_attr_separator] = ACTIONS(1),
    [sym_list_dash] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_nb_whitespace] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_non_lt_char] = ACTIONS(1),
    [sym_p_section_token] = ACTIONS(1),
    [sym_section_start_end_token] = ACTIONS(1),
    [sym_todo_left_bracket] = ACTIONS(1),
    [sym_todo_right_bracket] = ACTIONS(1),
    [sym_todo_checkmark] = ACTIONS(1),
    [sym_code_body] = ACTIONS(1),
    [sym_html_body] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(73),
    [sym_code_end_section] = STATE(3),
    [sym_code_start_section] = STATE(3),
    [sym_html_end_section] = STATE(3),
    [sym_html_start_section] = STATE(3),
    [sym_list_section] = STATE(3),
    [sym_p_section] = STATE(3),
    [sym_title_section] = STATE(3),
    [sym_todo_section] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_section_dashes] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(10), 1,
      sym_non_lt_char,
    STATE(2), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
    STATE(87), 1,
      sym_paragraph_body,
    ACTIONS(5), 3,
      ts_builtin_sym_end,
      sym_section_dashes,
      sym_todo_left_bracket,
  [30] = 3,
    ACTIONS(3), 1,
      sym_section_dashes,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(5), 9,
      sym_code_end_section,
      sym_code_start_section,
      sym_html_end_section,
      sym_html_start_section,
      sym_list_section,
      sym_p_section,
      sym_title_section,
      sym_todo_section,
      aux_sym_source_file_repeat1,
  [48] = 9,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      sym_non_lt_char,
    STATE(2), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
    STATE(87), 1,
      sym_paragraph_body,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      sym_section_dashes,
      sym_todo_left_bracket,
  [78] = 3,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_section_dashes,
    STATE(5), 9,
      sym_code_end_section,
      sym_code_start_section,
      sym_html_end_section,
      sym_html_start_section,
      sym_list_section,
      sym_p_section,
      sym_title_section,
      sym_todo_section,
      aux_sym_source_file_repeat1,
  [96] = 4,
    ACTIONS(28), 1,
      sym_todo_left_bracket,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(6), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(75), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [113] = 4,
    ACTIONS(33), 1,
      sym_todo_left_bracket,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(6), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(75), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [130] = 8,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      sym_non_lt_char,
    STATE(4), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
    STATE(87), 1,
      sym_paragraph_body,
  [155] = 4,
    ACTIONS(33), 1,
      sym_todo_left_bracket,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(6), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(75), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [172] = 7,
    ACTIONS(39), 1,
      sym_code_section_token,
    ACTIONS(41), 1,
      sym_html_section_token,
    ACTIONS(43), 1,
      sym_list_section_token,
    ACTIONS(45), 1,
      sym_p_section_token,
    ACTIONS(47), 1,
      sym_section_start_end_token,
    ACTIONS(49), 1,
      sym_title_section_token,
    ACTIONS(51), 1,
      sym_todo_section_token,
  [194] = 7,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(56), 1,
      sym_newline,
    ACTIONS(58), 1,
      sym_non_lt_char,
    STATE(11), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
  [216] = 7,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      sym_non_lt_char,
    ACTIONS(61), 1,
      sym_newline,
    STATE(11), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
  [238] = 5,
    ACTIONS(65), 1,
      sym_list_dash,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(16), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [256] = 7,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      sym_non_lt_char,
    ACTIONS(69), 1,
      sym_newline,
    STATE(11), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
  [278] = 7,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      sym_non_lt_char,
    ACTIONS(71), 1,
      sym_newline,
    STATE(14), 1,
      aux_sym_paragraph_repeat1,
    STATE(55), 1,
      sym_word,
    STATE(80), 1,
      sym_lt_with_non_lt_char,
    STATE(81), 1,
      sym_initial_word_chars,
  [300] = 5,
    ACTIONS(67), 1,
      sym_non_lt_char,
    ACTIONS(75), 1,
      sym_list_dash,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [318] = 5,
    ACTIONS(79), 1,
      sym_list_dash,
    ACTIONS(81), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [336] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [351] = 3,
    ACTIONS(86), 1,
      sym_attr_dashes,
    ACTIONS(89), 1,
      sym_newline,
    STATE(19), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [364] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(93), 1,
      sym_newline,
    STATE(31), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [377] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(95), 1,
      sym_newline,
    STATE(33), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [390] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(30), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [405] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [420] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(23), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [435] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(101), 1,
      sym_newline,
    STATE(19), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [448] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [463] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(105), 1,
      sym_newline,
    STATE(19), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [476] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [491] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [506] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(17), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [521] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(113), 1,
      sym_newline,
    STATE(19), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [534] = 3,
    ACTIONS(33), 1,
      sym_todo_left_bracket,
    STATE(7), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(75), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [547] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(115), 1,
      sym_newline,
    STATE(19), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [560] = 3,
    ACTIONS(33), 1,
      sym_todo_left_bracket,
    STATE(9), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(75), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [573] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(117), 1,
      sym_newline,
    STATE(25), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [586] = 3,
    ACTIONS(91), 1,
      sym_attr_dashes,
    ACTIONS(119), 1,
      sym_newline,
    STATE(27), 4,
      sym__attr,
      sym_attr_kv_pair,
      sym_attr_bool,
      aux_sym_list_section_repeat1,
  [599] = 3,
    ACTIONS(123), 1,
      sym_list_dash,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(37), 2,
      sym_list_item,
      aux_sym_list_section_repeat2,
  [611] = 3,
    ACTIONS(128), 1,
      sym_list_dash,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(37), 2,
      sym_list_item,
      aux_sym_list_section_repeat2,
  [623] = 3,
    ACTIONS(128), 1,
      sym_list_dash,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(37), 2,
      sym_list_item,
      aux_sym_list_section_repeat2,
  [635] = 2,
    ACTIONS(132), 1,
      sym_non_lt_char,
    ACTIONS(5), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_section_dashes,
      sym_todo_left_bracket,
  [645] = 2,
    ACTIONS(136), 1,
      sym_list_dash,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [654] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(24), 1,
      sym_headline,
    STATE(51), 1,
      sym_paragraph,
    STATE(52), 1,
      sym_paragraph_first_word,
  [667] = 3,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    STATE(26), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [678] = 3,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    STATE(29), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [689] = 3,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    STATE(28), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [700] = 3,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(52), 1,
      sym_paragraph_first_word,
    STATE(18), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [711] = 4,
    ACTIONS(67), 1,
      sym_non_lt_char,
    STATE(22), 1,
      sym_headline,
    STATE(51), 1,
      sym_paragraph,
    STATE(52), 1,
      sym_paragraph_first_word,
  [724] = 2,
    ACTIONS(140), 1,
      sym_list_dash,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [733] = 3,
    ACTIONS(142), 1,
      sym_todo_right_bracket,
    ACTIONS(144), 1,
      sym_todo_checkmark,
    ACTIONS(146), 1,
      sym_not_a_checkmark,
  [743] = 2,
    ACTIONS(148), 1,
      sym_list_dash,
    STATE(38), 2,
      sym_list_item,
      aux_sym_list_section_repeat2,
  [751] = 1,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [757] = 3,
    ACTIONS(152), 1,
      sym_nb_whitespace,
    ACTIONS(154), 1,
      sym_newline,
    STATE(15), 1,
      sym__wordbreak,
  [767] = 1,
    ACTIONS(56), 3,
      anon_sym_LT,
      sym_newline,
      sym_non_lt_char,
  [773] = 2,
    ACTIONS(148), 1,
      sym_list_dash,
    STATE(39), 2,
      sym_list_item,
      aux_sym_list_section_repeat2,
  [781] = 3,
    ACTIONS(156), 1,
      sym_nb_whitespace,
    ACTIONS(158), 1,
      sym_newline,
    STATE(53), 1,
      sym__wordbreak,
  [791] = 1,
    ACTIONS(160), 2,
      sym_attr_dashes,
      sym_newline,
  [796] = 1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [801] = 1,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [806] = 2,
    ACTIONS(166), 1,
      sym_attr_separator,
    ACTIONS(168), 1,
      sym_newline,
  [813] = 2,
    ACTIONS(170), 1,
      sym_nb_whitespace,
    ACTIONS(172), 1,
      sym_newline,
  [820] = 2,
    ACTIONS(174), 1,
      sym_code_section_token,
    ACTIONS(176), 1,
      sym_html_section_token,
  [827] = 2,
    ACTIONS(178), 1,
      sym_nb_whitespace,
    ACTIONS(180), 1,
      sym_newline,
  [834] = 2,
    ACTIONS(182), 1,
      aux_sym_attr_bool_token1,
    STATE(99), 1,
      sym_attr_key,
  [841] = 1,
    ACTIONS(184), 2,
      sym_attr_dashes,
      sym_newline,
  [846] = 1,
    ACTIONS(186), 1,
      sym_newline,
  [850] = 1,
    ACTIONS(188), 1,
      sym_code_body,
  [854] = 1,
    ACTIONS(190), 1,
      sym_newline,
  [858] = 1,
    ACTIONS(192), 1,
      sym_nb_whitespace,
  [862] = 1,
    ACTIONS(194), 1,
      sym_nb_whitespace,
  [866] = 1,
    ACTIONS(196), 1,
      sym_todo_right_bracket,
  [870] = 1,
    ACTIONS(198), 1,
      sym_todo_right_bracket,
  [874] = 1,
    ACTIONS(200), 1,
      sym_newline,
  [878] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [882] = 1,
    ACTIONS(204), 1,
      sym_newline,
  [886] = 1,
    ACTIONS(206), 1,
      sym_nb_whitespace,
  [890] = 1,
    ACTIONS(208), 1,
      sym_nb_whitespace,
  [894] = 1,
    ACTIONS(210), 1,
      sym_newline,
  [898] = 1,
    ACTIONS(212), 1,
      sym_non_lt_char,
  [902] = 1,
    ACTIONS(214), 1,
      sym_newline,
  [906] = 1,
    ACTIONS(216), 1,
      sym_following_word_chars,
  [910] = 1,
    ACTIONS(218), 1,
      sym_following_word_chars,
  [914] = 1,
    ACTIONS(220), 1,
      sym_newline,
  [918] = 1,
    ACTIONS(222), 1,
      sym_newline,
  [922] = 1,
    ACTIONS(224), 1,
      sym_newline,
  [926] = 1,
    ACTIONS(226), 1,
      sym_nb_whitespace,
  [930] = 1,
    ACTIONS(228), 1,
      sym_nb_whitespace,
  [934] = 1,
    ACTIONS(230), 1,
      sym_newline,
  [938] = 1,
    ACTIONS(232), 1,
      sym_newline,
  [942] = 1,
    ACTIONS(234), 1,
      sym_html_body,
  [946] = 1,
    ACTIONS(236), 1,
      sym_attr_value,
  [950] = 1,
    ACTIONS(238), 1,
      sym_following_word_chars,
  [954] = 1,
    ACTIONS(240), 1,
      sym_nb_whitespace,
  [958] = 1,
    ACTIONS(242), 1,
      sym_following_word_chars,
  [962] = 1,
    ACTIONS(244), 1,
      sym_newline,
  [966] = 1,
    ACTIONS(246), 1,
      sym_newline,
  [970] = 1,
    ACTIONS(248), 1,
      sym_section_start_end_token,
  [974] = 1,
    ACTIONS(250), 1,
      sym_section_start_end_token,
  [978] = 1,
    ACTIONS(252), 1,
      sym_newline,
  [982] = 1,
    ACTIONS(254), 1,
      sym_attr_separator,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 113,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 155,
  [SMALL_STATE(10)] = 172,
  [SMALL_STATE(11)] = 194,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 278,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 318,
  [SMALL_STATE(18)] = 336,
  [SMALL_STATE(19)] = 351,
  [SMALL_STATE(20)] = 364,
  [SMALL_STATE(21)] = 377,
  [SMALL_STATE(22)] = 390,
  [SMALL_STATE(23)] = 405,
  [SMALL_STATE(24)] = 420,
  [SMALL_STATE(25)] = 435,
  [SMALL_STATE(26)] = 448,
  [SMALL_STATE(27)] = 463,
  [SMALL_STATE(28)] = 476,
  [SMALL_STATE(29)] = 491,
  [SMALL_STATE(30)] = 506,
  [SMALL_STATE(31)] = 521,
  [SMALL_STATE(32)] = 534,
  [SMALL_STATE(33)] = 547,
  [SMALL_STATE(34)] = 560,
  [SMALL_STATE(35)] = 573,
  [SMALL_STATE(36)] = 586,
  [SMALL_STATE(37)] = 599,
  [SMALL_STATE(38)] = 611,
  [SMALL_STATE(39)] = 623,
  [SMALL_STATE(40)] = 635,
  [SMALL_STATE(41)] = 645,
  [SMALL_STATE(42)] = 654,
  [SMALL_STATE(43)] = 667,
  [SMALL_STATE(44)] = 678,
  [SMALL_STATE(45)] = 689,
  [SMALL_STATE(46)] = 700,
  [SMALL_STATE(47)] = 711,
  [SMALL_STATE(48)] = 724,
  [SMALL_STATE(49)] = 733,
  [SMALL_STATE(50)] = 743,
  [SMALL_STATE(51)] = 751,
  [SMALL_STATE(52)] = 757,
  [SMALL_STATE(53)] = 767,
  [SMALL_STATE(54)] = 773,
  [SMALL_STATE(55)] = 781,
  [SMALL_STATE(56)] = 791,
  [SMALL_STATE(57)] = 796,
  [SMALL_STATE(58)] = 801,
  [SMALL_STATE(59)] = 806,
  [SMALL_STATE(60)] = 813,
  [SMALL_STATE(61)] = 820,
  [SMALL_STATE(62)] = 827,
  [SMALL_STATE(63)] = 834,
  [SMALL_STATE(64)] = 841,
  [SMALL_STATE(65)] = 846,
  [SMALL_STATE(66)] = 850,
  [SMALL_STATE(67)] = 854,
  [SMALL_STATE(68)] = 858,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 866,
  [SMALL_STATE(71)] = 870,
  [SMALL_STATE(72)] = 874,
  [SMALL_STATE(73)] = 878,
  [SMALL_STATE(74)] = 882,
  [SMALL_STATE(75)] = 886,
  [SMALL_STATE(76)] = 890,
  [SMALL_STATE(77)] = 894,
  [SMALL_STATE(78)] = 898,
  [SMALL_STATE(79)] = 902,
  [SMALL_STATE(80)] = 906,
  [SMALL_STATE(81)] = 910,
  [SMALL_STATE(82)] = 914,
  [SMALL_STATE(83)] = 918,
  [SMALL_STATE(84)] = 922,
  [SMALL_STATE(85)] = 926,
  [SMALL_STATE(86)] = 930,
  [SMALL_STATE(87)] = 934,
  [SMALL_STATE(88)] = 938,
  [SMALL_STATE(89)] = 942,
  [SMALL_STATE(90)] = 946,
  [SMALL_STATE(91)] = 950,
  [SMALL_STATE(92)] = 954,
  [SMALL_STATE(93)] = 958,
  [SMALL_STATE(94)] = 962,
  [SMALL_STATE(95)] = 966,
  [SMALL_STATE(96)] = 970,
  [SMALL_STATE(97)] = 974,
  [SMALL_STATE(98)] = 978,
  [SMALL_STATE(99)] = 982,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_todo_item_repeat1, 2),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_todo_item_repeat1, 2), SHIFT_REPEAT(78),
  [10] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_todo_item_repeat1, 2), SHIFT_REPEAT(80),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_item, 3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_todo_section_repeat1, 2),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_todo_section_repeat1, 2), SHIFT_REPEAT(49),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_section, 5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_section, 6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(78),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(80),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_body, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_end_section_repeat1, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_end_section_repeat1, 2),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_end_section_repeat1, 2), SHIFT_REPEAT(93),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_end_section, 6),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_section_repeat1, 2), SHIFT_REPEAT(68),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_section_repeat1, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 6),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 5),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_p_section, 5),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_end_section, 6),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_p_section, 6),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_section_repeat2, 2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_section_repeat2, 2), SHIFT_REPEAT(92),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_section, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_section, 6),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_todo_item_repeat1, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 4),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 1, .production_id = 1),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_kv_pair, 7),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_start_section, 6),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_section, 6),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_key, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph_first_word, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_first_word, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_bool, 4),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_todo_bracket, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_initial_word_chars, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_todo_bracket, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_progress_todo_bracket, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lt_with_non_lt_char, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_code_body = 0,
  ts_external_token_html_body = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_code_body] = sym_code_body,
  [ts_external_token_html_body] = sym_html_body,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_code_body] = true,
    [ts_external_token_html_body] = true,
  },
  [2] = {
    [ts_external_token_code_body] = true,
  },
  [3] = {
    [ts_external_token_html_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_neopolitan_external_scanner_create(void);
void tree_sitter_neopolitan_external_scanner_destroy(void *);
bool tree_sitter_neopolitan_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_neopolitan_external_scanner_serialize(void *, char *);
void tree_sitter_neopolitan_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_neopolitan(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_neopolitan_external_scanner_create,
      tree_sitter_neopolitan_external_scanner_destroy,
      tree_sitter_neopolitan_external_scanner_scan,
      tree_sitter_neopolitan_external_scanner_serialize,
      tree_sitter_neopolitan_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
