#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 1
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  aux_sym_attr_bool_value_token1 = 1,
  sym_attr_dashes = 2,
  sym_attr_separator = 3,
  sym_attr_value = 4,
  sym_code_section_token = 5,
  sym_list_dash = 6,
  anon_sym_LT = 7,
  sym_following_word_chars = 8,
  sym_nb_whitespace = 9,
  sym_newline = 10,
  sym_non_lt_char = 11,
  sym_section_dashes = 12,
  sym_section_start_end_token = 13,
  sym_todo_left_bracket = 14,
  sym_todo_right_bracket = 15,
  sym_todo_checkmark = 16,
  sym_not_a_checkmark = 17,
  sym_code_body = 18,
  sym_html_container_body = 19,
  sym_html_section_body = 20,
  sym_html_token = 21,
  sym_list_token = 22,
  sym_p_token = 23,
  sym_single_space = 24,
  sym_title_token = 25,
  sym_todo_token = 26,
  sym_error_sentinel = 27,
  sym_source_file = 28,
  sym__attr = 29,
  sym_attr_kv_pair = 30,
  sym_attr_bool = 31,
  sym_attr_bool_value = 32,
  sym_attr_key = 33,
  sym_code_end_section = 34,
  sym_code_start_section = 35,
  sym_headline = 36,
  sym_html_section = 37,
  sym_initial_word_chars = 38,
  sym_list_item = 39,
  sym_list_section = 40,
  sym_lt_with_non_lt_char = 41,
  sym_p_section = 42,
  sym_paragraph = 43,
  sym_paragraph_body = 44,
  sym_paragraph_first_word = 45,
  sym_title_section = 46,
  sym_empty_todo_bracket = 47,
  sym_completed_todo_bracket = 48,
  sym_in_progress_todo_bracket = 49,
  sym_todo_item = 50,
  sym_todo_section = 51,
  sym_word = 52,
  sym__wordbreak = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_code_end_section_repeat1 = 55,
  aux_sym_code_start_section_repeat1 = 56,
  aux_sym_list_section_repeat1 = 57,
  aux_sym_paragraph_repeat1 = 58,
  aux_sym_todo_item_repeat1 = 59,
  aux_sym_todo_section_repeat1 = 60,
  anon_alias_sym_headline = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_attr_bool_value_token1] = "attr_bool_value_token1",
  [sym_attr_dashes] = "attr_dashes",
  [sym_attr_separator] = "attr_separator",
  [sym_attr_value] = "attr_value",
  [sym_code_section_token] = "code_section_token",
  [sym_list_dash] = "list_dash",
  [anon_sym_LT] = "<",
  [sym_following_word_chars] = "following_word_chars",
  [sym_nb_whitespace] = "nb_whitespace",
  [sym_newline] = "newline",
  [sym_non_lt_char] = "non_lt_char",
  [sym_section_dashes] = "section_dashes",
  [sym_section_start_end_token] = "section_start_end_token",
  [sym_todo_left_bracket] = "todo_left_bracket",
  [sym_todo_right_bracket] = "todo_right_bracket",
  [sym_todo_checkmark] = "todo_checkmark",
  [sym_not_a_checkmark] = "not_a_checkmark",
  [sym_code_body] = "code_body",
  [sym_html_container_body] = "html_container_body",
  [sym_html_section_body] = "html_section_body",
  [sym_html_token] = "html_token",
  [sym_list_token] = "list_token",
  [sym_p_token] = "p_token",
  [sym_single_space] = "single_space",
  [sym_title_token] = "title_token",
  [sym_todo_token] = "todo_token",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym__attr] = "_attr",
  [sym_attr_kv_pair] = "attr_kv_pair",
  [sym_attr_bool] = "attr_bool",
  [sym_attr_bool_value] = "attr_bool_value",
  [sym_attr_key] = "attr_key",
  [sym_code_end_section] = "code_end_section",
  [sym_code_start_section] = "code_start_section",
  [sym_headline] = "headline",
  [sym_html_section] = "html_section",
  [sym_initial_word_chars] = "initial_word_chars",
  [sym_list_item] = "list_item",
  [sym_list_section] = "list_section",
  [sym_lt_with_non_lt_char] = "lt_with_non_lt_char",
  [sym_p_section] = "p_section",
  [sym_paragraph] = "paragraph",
  [sym_paragraph_body] = "paragraph_body",
  [sym_paragraph_first_word] = "paragraph_first_word",
  [sym_title_section] = "title_section",
  [sym_empty_todo_bracket] = "empty_todo_bracket",
  [sym_completed_todo_bracket] = "completed_todo_bracket",
  [sym_in_progress_todo_bracket] = "in_progress_todo_bracket",
  [sym_todo_item] = "todo_item",
  [sym_todo_section] = "todo_section",
  [sym_word] = "word",
  [sym__wordbreak] = "_wordbreak",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_code_end_section_repeat1] = "code_end_section_repeat1",
  [aux_sym_code_start_section_repeat1] = "code_start_section_repeat1",
  [aux_sym_list_section_repeat1] = "list_section_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_todo_item_repeat1] = "todo_item_repeat1",
  [aux_sym_todo_section_repeat1] = "todo_section_repeat1",
  [anon_alias_sym_headline] = "headline",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_attr_bool_value_token1] = aux_sym_attr_bool_value_token1,
  [sym_attr_dashes] = sym_attr_dashes,
  [sym_attr_separator] = sym_attr_separator,
  [sym_attr_value] = sym_attr_value,
  [sym_code_section_token] = sym_code_section_token,
  [sym_list_dash] = sym_list_dash,
  [anon_sym_LT] = anon_sym_LT,
  [sym_following_word_chars] = sym_following_word_chars,
  [sym_nb_whitespace] = sym_nb_whitespace,
  [sym_newline] = sym_newline,
  [sym_non_lt_char] = sym_non_lt_char,
  [sym_section_dashes] = sym_section_dashes,
  [sym_section_start_end_token] = sym_section_start_end_token,
  [sym_todo_left_bracket] = sym_todo_left_bracket,
  [sym_todo_right_bracket] = sym_todo_right_bracket,
  [sym_todo_checkmark] = sym_todo_checkmark,
  [sym_not_a_checkmark] = sym_not_a_checkmark,
  [sym_code_body] = sym_code_body,
  [sym_html_container_body] = sym_html_container_body,
  [sym_html_section_body] = sym_html_section_body,
  [sym_html_token] = sym_html_token,
  [sym_list_token] = sym_list_token,
  [sym_p_token] = sym_p_token,
  [sym_single_space] = sym_single_space,
  [sym_title_token] = sym_title_token,
  [sym_todo_token] = sym_todo_token,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym__attr] = sym__attr,
  [sym_attr_kv_pair] = sym_attr_kv_pair,
  [sym_attr_bool] = sym_attr_bool,
  [sym_attr_bool_value] = sym_attr_bool_value,
  [sym_attr_key] = sym_attr_key,
  [sym_code_end_section] = sym_code_end_section,
  [sym_code_start_section] = sym_code_start_section,
  [sym_headline] = sym_headline,
  [sym_html_section] = sym_html_section,
  [sym_initial_word_chars] = sym_initial_word_chars,
  [sym_list_item] = sym_list_item,
  [sym_list_section] = sym_list_section,
  [sym_lt_with_non_lt_char] = sym_lt_with_non_lt_char,
  [sym_p_section] = sym_p_section,
  [sym_paragraph] = sym_paragraph,
  [sym_paragraph_body] = sym_paragraph_body,
  [sym_paragraph_first_word] = sym_paragraph_first_word,
  [sym_title_section] = sym_title_section,
  [sym_empty_todo_bracket] = sym_empty_todo_bracket,
  [sym_completed_todo_bracket] = sym_completed_todo_bracket,
  [sym_in_progress_todo_bracket] = sym_in_progress_todo_bracket,
  [sym_todo_item] = sym_todo_item,
  [sym_todo_section] = sym_todo_section,
  [sym_word] = sym_word,
  [sym__wordbreak] = sym__wordbreak,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_code_end_section_repeat1] = aux_sym_code_end_section_repeat1,
  [aux_sym_code_start_section_repeat1] = aux_sym_code_start_section_repeat1,
  [aux_sym_list_section_repeat1] = aux_sym_list_section_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_todo_item_repeat1] = aux_sym_todo_item_repeat1,
  [aux_sym_todo_section_repeat1] = aux_sym_todo_section_repeat1,
  [anon_alias_sym_headline] = anon_alias_sym_headline,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_attr_bool_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_attr_dashes] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_value] = {
    .visible = true,
    .named = true,
  },
  [sym_code_section_token] = {
    .visible = true,
    .named = true,
  },
  [sym_list_dash] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_following_word_chars] = {
    .visible = true,
    .named = true,
  },
  [sym_nb_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_non_lt_char] = {
    .visible = true,
    .named = true,
  },
  [sym_section_dashes] = {
    .visible = true,
    .named = true,
  },
  [sym_section_start_end_token] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_left_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_right_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_checkmark] = {
    .visible = true,
    .named = true,
  },
  [sym_not_a_checkmark] = {
    .visible = true,
    .named = true,
  },
  [sym_code_body] = {
    .visible = true,
    .named = true,
  },
  [sym_html_container_body] = {
    .visible = true,
    .named = true,
  },
  [sym_html_section_body] = {
    .visible = true,
    .named = true,
  },
  [sym_html_token] = {
    .visible = true,
    .named = true,
  },
  [sym_list_token] = {
    .visible = true,
    .named = true,
  },
  [sym_p_token] = {
    .visible = true,
    .named = true,
  },
  [sym_single_space] = {
    .visible = true,
    .named = true,
  },
  [sym_title_token] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_token] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__attr] = {
    .visible = false,
    .named = true,
  },
  [sym_attr_kv_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_bool_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_key] = {
    .visible = true,
    .named = true,
  },
  [sym_code_end_section] = {
    .visible = true,
    .named = true,
  },
  [sym_code_start_section] = {
    .visible = true,
    .named = true,
  },
  [sym_headline] = {
    .visible = true,
    .named = true,
  },
  [sym_html_section] = {
    .visible = true,
    .named = true,
  },
  [sym_initial_word_chars] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_list_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lt_with_non_lt_char] = {
    .visible = true,
    .named = true,
  },
  [sym_p_section] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_body] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph_first_word] = {
    .visible = true,
    .named = true,
  },
  [sym_title_section] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_in_progress_todo_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_item] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_section] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym__wordbreak] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_end_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_start_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_todo_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_todo_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_headline] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attr_bool = 1,
  field_attr_bool_value = 2,
  field_code_body = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr_bool] = "attr_bool",
  [field_attr_bool_value] = "attr_bool_value",
  [field_code_body] = "code_body",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_attr_bool, 0, .inherited = true},
  [1] =
    {field_attr_bool, 0},
  [2] =
    {field_attr_bool, 0, .inherited = true},
    {field_attr_bool, 1, .inherited = true},
  [4] =
    {field_attr_bool, 4, .inherited = true},
  [5] =
    {field_code_body, 6},
  [6] =
    {field_attr_bool_value, 2},
  [7] =
    {field_attr_bool, 5, .inherited = true},
    {field_code_body, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [0] = anon_alias_sym_headline,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_paragraph, 2,
    sym_paragraph,
    anon_alias_sym_headline,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\t') ADVANCE(25);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(31);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(27);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == ']') ADVANCE(31);
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(31);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t') ADVANCE(27);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_attr_bool_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_attr_dashes);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_attr_separator);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_attr_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_code_section_token);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_list_dash);
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_list_dash);
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_following_word_chars);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_nb_whitespace);
      if (lookahead == '\t') ADVANCE(25);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_nb_whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_non_lt_char);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_section_dashes);
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_section_start_end_token);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_todo_left_bracket);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_todo_right_bracket);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_todo_checkmark);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_not_a_checkmark);
      if (lookahead != 0 &&
          lookahead != 'X' &&
          lookahead != ']' &&
          lookahead != 'x') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13, .external_lex_state = 2},
  [2] = {.lex_state = 13, .external_lex_state = 2},
  [3] = {.lex_state = 13, .external_lex_state = 2},
  [4] = {.lex_state = 13, .external_lex_state = 2},
  [5] = {.lex_state = 13, .external_lex_state = 2},
  [6] = {.lex_state = 13, .external_lex_state = 2},
  [7] = {.lex_state = 13, .external_lex_state = 2},
  [8] = {.lex_state = 13, .external_lex_state = 2},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 2, .external_lex_state = 3},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12, .external_lex_state = 2},
  [15] = {.lex_state = 12, .external_lex_state = 2},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12, .external_lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 12, .external_lex_state = 2},
  [21] = {.lex_state = 12, .external_lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 12, .external_lex_state = 2},
  [24] = {.lex_state = 12, .external_lex_state = 2},
  [25] = {.lex_state = 12, .external_lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 12, .external_lex_state = 2},
  [39] = {.lex_state = 12, .external_lex_state = 2},
  [40] = {.lex_state = 13, .external_lex_state = 2},
  [41] = {.lex_state = 13, .external_lex_state = 2},
  [42] = {.lex_state = 13, .external_lex_state = 2},
  [43] = {.lex_state = 13, .external_lex_state = 2},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 12},
  [47] = {.lex_state = 12, .external_lex_state = 2},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 12, .external_lex_state = 2},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 12, .external_lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 13, .external_lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 13, .external_lex_state = 2},
  [65] = {.lex_state = 13, .external_lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 13, .external_lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 5},
  [79] = {.lex_state = 13},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 13},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 12},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 9},
  [87] = {.lex_state = 9},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 13},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 13},
  [92] = {.lex_state = 13},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 11},
  [98] = {.lex_state = 9},
  [99] = {.lex_state = 0, .external_lex_state = 5},
  [100] = {.lex_state = 0, .external_lex_state = 6},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 9},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_attr_dashes] = ACTIONS(1),
    [sym_attr_separator] = ACTIONS(1),
    [sym_list_dash] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_nb_whitespace] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_non_lt_char] = ACTIONS(1),
    [sym_section_start_end_token] = ACTIONS(1),
    [sym_todo_left_bracket] = ACTIONS(1),
    [sym_todo_right_bracket] = ACTIONS(1),
    [sym_todo_checkmark] = ACTIONS(1),
    [sym_code_body] = ACTIONS(1),
    [sym_html_container_body] = ACTIONS(1),
    [sym_html_section_body] = ACTIONS(1),
    [sym_html_token] = ACTIONS(1),
    [sym_list_token] = ACTIONS(1),
    [sym_p_token] = ACTIONS(1),
    [sym_single_space] = ACTIONS(1),
    [sym_title_token] = ACTIONS(1),
    [sym_todo_token] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(104),
    [sym_code_end_section] = STATE(4),
    [sym_code_start_section] = STATE(4),
    [sym_html_section] = STATE(4),
    [sym_list_section] = STATE(4),
    [sym_p_section] = STATE(4),
    [sym_title_section] = STATE(4),
    [sym_todo_section] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_section_dashes] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(10), 1,
      sym_non_lt_char,
    STATE(2), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
    STATE(93), 1,
      sym_paragraph_body,
    ACTIONS(5), 3,
      ts_builtin_sym_end,
      sym_section_dashes,
      sym_todo_left_bracket,
  [30] = 9,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_non_lt_char,
    STATE(2), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
    STATE(93), 1,
      sym_paragraph_body,
    ACTIONS(13), 3,
      ts_builtin_sym_end,
      sym_section_dashes,
      sym_todo_left_bracket,
  [60] = 3,
    ACTIONS(3), 1,
      sym_section_dashes,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(5), 8,
      sym_code_end_section,
      sym_code_start_section,
      sym_html_section,
      sym_list_section,
      sym_p_section,
      sym_title_section,
      sym_todo_section,
      aux_sym_source_file_repeat1,
  [77] = 3,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_section_dashes,
    STATE(5), 8,
      sym_code_end_section,
      sym_code_start_section,
      sym_html_section,
      sym_list_section,
      sym_p_section,
      sym_title_section,
      sym_todo_section,
      aux_sym_source_file_repeat1,
  [94] = 4,
    ACTIONS(28), 1,
      sym_todo_left_bracket,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(8), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(101), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [111] = 4,
    ACTIONS(28), 1,
      sym_todo_left_bracket,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(8), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(101), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [128] = 4,
    ACTIONS(34), 1,
      sym_todo_left_bracket,
    ACTIONS(32), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(8), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(101), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [145] = 8,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      sym_non_lt_char,
    STATE(3), 1,
      aux_sym_todo_item_repeat1,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
    STATE(93), 1,
      sym_paragraph_body,
  [170] = 7,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(42), 1,
      sym_newline,
    ACTIONS(44), 1,
      sym_non_lt_char,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
  [192] = 7,
    ACTIONS(47), 1,
      sym_code_section_token,
    ACTIONS(49), 1,
      sym_section_start_end_token,
    ACTIONS(51), 1,
      sym_html_token,
    ACTIONS(53), 1,
      sym_list_token,
    ACTIONS(55), 1,
      sym_p_token,
    ACTIONS(57), 1,
      sym_title_token,
    ACTIONS(59), 1,
      sym_todo_token,
  [214] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      sym_non_lt_char,
    ACTIONS(61), 1,
      sym_newline,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
  [236] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      sym_non_lt_char,
    ACTIONS(63), 1,
      sym_newline,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
  [258] = 5,
    ACTIONS(67), 1,
      sym_list_dash,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [276] = 5,
    ACTIONS(73), 1,
      sym_list_dash,
    ACTIONS(75), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [294] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      sym_non_lt_char,
    ACTIONS(78), 1,
      sym_newline,
    STATE(13), 1,
      aux_sym_paragraph_repeat1,
    STATE(51), 1,
      sym_word,
    STATE(86), 1,
      sym_lt_with_non_lt_char,
    STATE(87), 1,
      sym_initial_word_chars,
  [316] = 5,
    ACTIONS(69), 1,
      sym_non_lt_char,
    ACTIONS(82), 1,
      sym_list_dash,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(14), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [334] = 3,
    ACTIONS(28), 1,
      sym_todo_left_bracket,
    STATE(7), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(101), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [347] = 5,
    ACTIONS(84), 1,
      sym_attr_dashes,
    ACTIONS(87), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [364] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [379] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [394] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(95), 1,
      sym_newline,
    STATE(26), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [411] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(20), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [426] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [441] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [456] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(103), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [473] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(105), 1,
      sym_newline,
    STATE(28), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [490] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(107), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [507] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(109), 1,
      sym_newline,
    STATE(30), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [524] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(111), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [541] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(113), 1,
      sym_newline,
    STATE(34), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [558] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(115), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [575] = 3,
    ACTIONS(28), 1,
      sym_todo_left_bracket,
    STATE(6), 2,
      sym_todo_item,
      aux_sym_todo_section_repeat1,
    STATE(101), 3,
      sym_empty_todo_bracket,
      sym_completed_todo_bracket,
      sym_in_progress_todo_bracket,
  [588] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(117), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [605] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(119), 1,
      sym_newline,
    STATE(37), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [622] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(121), 1,
      sym_newline,
    STATE(32), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [639] = 5,
    ACTIONS(93), 1,
      sym_attr_dashes,
    ACTIONS(123), 1,
      sym_newline,
    STATE(19), 1,
      aux_sym_code_start_section_repeat1,
    STATE(69), 1,
      sym_attr_bool,
    STATE(61), 2,
      sym__attr,
      sym_attr_kv_pair,
  [656] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(24), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [671] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(15), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [686] = 3,
    ACTIONS(131), 1,
      sym_list_dash,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(40), 2,
      sym_list_item,
      aux_sym_list_section_repeat1,
  [698] = 2,
    ACTIONS(134), 1,
      sym_non_lt_char,
    ACTIONS(5), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      sym_section_dashes,
      sym_todo_left_bracket,
  [708] = 3,
    ACTIONS(138), 1,
      sym_list_dash,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(40), 2,
      sym_list_item,
      aux_sym_list_section_repeat1,
  [720] = 3,
    ACTIONS(138), 1,
      sym_list_dash,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
    STATE(40), 2,
      sym_list_item,
      aux_sym_list_section_repeat1,
  [732] = 3,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    STATE(21), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [743] = 3,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    STATE(39), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [754] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(38), 1,
      sym_headline,
    STATE(55), 1,
      sym_paragraph,
    STATE(56), 1,
      sym_paragraph_first_word,
  [767] = 2,
    ACTIONS(144), 1,
      sym_list_dash,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [776] = 3,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(56), 1,
      sym_paragraph_first_word,
    STATE(25), 2,
      sym_paragraph,
      aux_sym_code_end_section_repeat1,
  [787] = 2,
    ACTIONS(148), 1,
      sym_list_dash,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [796] = 4,
    ACTIONS(69), 1,
      sym_non_lt_char,
    STATE(23), 1,
      sym_headline,
    STATE(55), 1,
      sym_paragraph,
    STATE(56), 1,
      sym_paragraph_first_word,
  [809] = 3,
    ACTIONS(150), 1,
      sym_nb_whitespace,
    ACTIONS(152), 1,
      sym_newline,
    STATE(52), 1,
      sym__wordbreak,
  [819] = 1,
    ACTIONS(42), 3,
      anon_sym_LT,
      sym_newline,
      sym_non_lt_char,
  [825] = 3,
    ACTIONS(154), 1,
      sym_todo_right_bracket,
    ACTIONS(156), 1,
      sym_todo_checkmark,
    ACTIONS(158), 1,
      sym_not_a_checkmark,
  [835] = 3,
    ACTIONS(160), 1,
      aux_sym_attr_bool_value_token1,
    STATE(85), 1,
      sym_attr_key,
    STATE(88), 1,
      sym_attr_bool_value,
  [845] = 1,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      sym_non_lt_char,
      sym_section_dashes,
  [851] = 3,
    ACTIONS(164), 1,
      sym_nb_whitespace,
    ACTIONS(166), 1,
      sym_newline,
    STATE(16), 1,
      sym__wordbreak,
  [861] = 2,
    ACTIONS(168), 1,
      sym_list_dash,
    STATE(43), 2,
      sym_list_item,
      aux_sym_list_section_repeat1,
  [869] = 2,
    ACTIONS(168), 1,
      sym_list_dash,
    STATE(42), 2,
      sym_list_item,
      aux_sym_list_section_repeat1,
  [877] = 2,
    ACTIONS(170), 1,
      sym_nb_whitespace,
    ACTIONS(172), 1,
      sym_newline,
  [884] = 1,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [889] = 1,
    ACTIONS(176), 2,
      sym_attr_dashes,
      sym_newline,
  [894] = 1,
    ACTIONS(178), 2,
      sym_attr_dashes,
      sym_newline,
  [899] = 2,
    ACTIONS(180), 1,
      sym_attr_separator,
    ACTIONS(182), 1,
      sym_newline,
  [906] = 1,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [911] = 1,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [916] = 1,
    ACTIONS(188), 2,
      sym_attr_dashes,
      sym_newline,
  [921] = 1,
    ACTIONS(190), 2,
      ts_builtin_sym_end,
      sym_section_dashes,
  [926] = 2,
    ACTIONS(192), 1,
      sym_nb_whitespace,
    ACTIONS(194), 1,
      sym_newline,
  [933] = 1,
    ACTIONS(196), 2,
      sym_attr_dashes,
      sym_newline,
  [938] = 1,
    ACTIONS(198), 1,
      sym_todo_right_bracket,
  [942] = 1,
    ACTIONS(200), 1,
      sym_newline,
  [946] = 1,
    ACTIONS(202), 1,
      sym_todo_right_bracket,
  [950] = 1,
    ACTIONS(204), 1,
      sym_newline,
  [954] = 1,
    ACTIONS(206), 1,
      sym_html_section_body,
  [958] = 1,
    ACTIONS(208), 1,
      sym_code_section_token,
  [962] = 1,
    ACTIONS(210), 1,
      sym_section_start_end_token,
  [966] = 1,
    ACTIONS(212), 1,
      sym_html_section_body,
  [970] = 1,
    ACTIONS(214), 1,
      sym_code_body,
  [974] = 1,
    ACTIONS(216), 1,
      sym_nb_whitespace,
  [978] = 1,
    ACTIONS(218), 1,
      sym_newline,
  [982] = 1,
    ACTIONS(220), 1,
      sym_nb_whitespace,
  [986] = 1,
    ACTIONS(222), 1,
      sym_newline,
  [990] = 1,
    ACTIONS(224), 1,
      sym_newline,
  [994] = 1,
    ACTIONS(226), 1,
      sym_non_lt_char,
  [998] = 1,
    ACTIONS(228), 1,
      sym_attr_separator,
  [1002] = 1,
    ACTIONS(230), 1,
      sym_following_word_chars,
  [1006] = 1,
    ACTIONS(232), 1,
      sym_following_word_chars,
  [1010] = 1,
    ACTIONS(234), 1,
      sym_newline,
  [1014] = 1,
    ACTIONS(236), 1,
      sym_nb_whitespace,
  [1018] = 1,
    ACTIONS(238), 1,
      sym_newline,
  [1022] = 1,
    ACTIONS(240), 1,
      sym_nb_whitespace,
  [1026] = 1,
    ACTIONS(242), 1,
      sym_nb_whitespace,
  [1030] = 1,
    ACTIONS(244), 1,
      sym_newline,
  [1034] = 1,
    ACTIONS(246), 1,
      sym_newline,
  [1038] = 1,
    ACTIONS(248), 1,
      sym_newline,
  [1042] = 1,
    ACTIONS(250), 1,
      sym_newline,
  [1046] = 1,
    ACTIONS(252), 1,
      sym_attr_value,
  [1050] = 1,
    ACTIONS(254), 1,
      sym_following_word_chars,
  [1054] = 1,
    ACTIONS(256), 1,
      sym_code_body,
  [1058] = 1,
    ACTIONS(258), 1,
      sym_single_space,
  [1062] = 1,
    ACTIONS(260), 1,
      sym_nb_whitespace,
  [1066] = 1,
    ACTIONS(262), 1,
      sym_newline,
  [1070] = 1,
    ACTIONS(264), 1,
      sym_following_word_chars,
  [1074] = 1,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
  [1078] = 1,
    ACTIONS(268), 1,
      sym_newline,
  [1082] = 1,
    ACTIONS(270), 1,
      sym_nb_whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 77,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 111,
  [SMALL_STATE(8)] = 128,
  [SMALL_STATE(9)] = 145,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 192,
  [SMALL_STATE(12)] = 214,
  [SMALL_STATE(13)] = 236,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 276,
  [SMALL_STATE(16)] = 294,
  [SMALL_STATE(17)] = 316,
  [SMALL_STATE(18)] = 334,
  [SMALL_STATE(19)] = 347,
  [SMALL_STATE(20)] = 364,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 394,
  [SMALL_STATE(23)] = 411,
  [SMALL_STATE(24)] = 426,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 456,
  [SMALL_STATE(27)] = 473,
  [SMALL_STATE(28)] = 490,
  [SMALL_STATE(29)] = 507,
  [SMALL_STATE(30)] = 524,
  [SMALL_STATE(31)] = 541,
  [SMALL_STATE(32)] = 558,
  [SMALL_STATE(33)] = 575,
  [SMALL_STATE(34)] = 588,
  [SMALL_STATE(35)] = 605,
  [SMALL_STATE(36)] = 622,
  [SMALL_STATE(37)] = 639,
  [SMALL_STATE(38)] = 656,
  [SMALL_STATE(39)] = 671,
  [SMALL_STATE(40)] = 686,
  [SMALL_STATE(41)] = 698,
  [SMALL_STATE(42)] = 708,
  [SMALL_STATE(43)] = 720,
  [SMALL_STATE(44)] = 732,
  [SMALL_STATE(45)] = 743,
  [SMALL_STATE(46)] = 754,
  [SMALL_STATE(47)] = 767,
  [SMALL_STATE(48)] = 776,
  [SMALL_STATE(49)] = 787,
  [SMALL_STATE(50)] = 796,
  [SMALL_STATE(51)] = 809,
  [SMALL_STATE(52)] = 819,
  [SMALL_STATE(53)] = 825,
  [SMALL_STATE(54)] = 835,
  [SMALL_STATE(55)] = 845,
  [SMALL_STATE(56)] = 851,
  [SMALL_STATE(57)] = 861,
  [SMALL_STATE(58)] = 869,
  [SMALL_STATE(59)] = 877,
  [SMALL_STATE(60)] = 884,
  [SMALL_STATE(61)] = 889,
  [SMALL_STATE(62)] = 894,
  [SMALL_STATE(63)] = 899,
  [SMALL_STATE(64)] = 906,
  [SMALL_STATE(65)] = 911,
  [SMALL_STATE(66)] = 916,
  [SMALL_STATE(67)] = 921,
  [SMALL_STATE(68)] = 926,
  [SMALL_STATE(69)] = 933,
  [SMALL_STATE(70)] = 938,
  [SMALL_STATE(71)] = 942,
  [SMALL_STATE(72)] = 946,
  [SMALL_STATE(73)] = 950,
  [SMALL_STATE(74)] = 954,
  [SMALL_STATE(75)] = 958,
  [SMALL_STATE(76)] = 962,
  [SMALL_STATE(77)] = 966,
  [SMALL_STATE(78)] = 970,
  [SMALL_STATE(79)] = 974,
  [SMALL_STATE(80)] = 978,
  [SMALL_STATE(81)] = 982,
  [SMALL_STATE(82)] = 986,
  [SMALL_STATE(83)] = 990,
  [SMALL_STATE(84)] = 994,
  [SMALL_STATE(85)] = 998,
  [SMALL_STATE(86)] = 1002,
  [SMALL_STATE(87)] = 1006,
  [SMALL_STATE(88)] = 1010,
  [SMALL_STATE(89)] = 1014,
  [SMALL_STATE(90)] = 1018,
  [SMALL_STATE(91)] = 1022,
  [SMALL_STATE(92)] = 1026,
  [SMALL_STATE(93)] = 1030,
  [SMALL_STATE(94)] = 1034,
  [SMALL_STATE(95)] = 1038,
  [SMALL_STATE(96)] = 1042,
  [SMALL_STATE(97)] = 1046,
  [SMALL_STATE(98)] = 1050,
  [SMALL_STATE(99)] = 1054,
  [SMALL_STATE(100)] = 1058,
  [SMALL_STATE(101)] = 1062,
  [SMALL_STATE(102)] = 1066,
  [SMALL_STATE(103)] = 1070,
  [SMALL_STATE(104)] = 1074,
  [SMALL_STATE(105)] = 1078,
  [SMALL_STATE(106)] = 1082,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_todo_item_repeat1, 2),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_todo_item_repeat1, 2), SHIFT_REPEAT(84),
  [10] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_todo_item_repeat1, 2), SHIFT_REPEAT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_item, 3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(100),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_section, 6),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_section, 7, .production_id = 5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_todo_section_repeat1, 2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_todo_section_repeat1, 2), SHIFT_REPEAT(53),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(84),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(86),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_body, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_end_section_repeat1, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_end_section_repeat1, 2),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_end_section_repeat1, 2), SHIFT_REPEAT(103),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_start_section_repeat1, 2, .production_id = 3), SHIFT_REPEAT(79),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_start_section_repeat1, 2, .production_id = 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 8, .production_id = 5),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_end_section, 7),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 7, .production_id = 5),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 7),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_p_section, 7, .production_id = 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_section, 6),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_p_section, 6),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_section_repeat1, 2),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_section_repeat1, 2), SHIFT_REPEAT(106),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_todo_item_repeat1, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_section, 6),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_section, 7, .production_id = 5),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 4),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 1, .production_id = 4),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_start_section, 8, .production_id = 8),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_start_section_repeat1, 1, .production_id = 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_kv_pair, 7),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_key, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_bool_value, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_section, 8, .production_id = 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_section, 7),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_bool, 4, .production_id = 7),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_start_section, 7, .production_id = 6),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph_first_word, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph_first_word, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__attr, 1, .production_id = 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_initial_word_chars, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_todo_bracket, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_todo_bracket, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_progress_todo_bracket, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lt_with_non_lt_char, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [266] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_code_body = 0,
  ts_external_token_html_container_body = 1,
  ts_external_token_html_section_body = 2,
  ts_external_token_html_token = 3,
  ts_external_token_list_token = 4,
  ts_external_token_p_token = 5,
  ts_external_token_section_dashes = 6,
  ts_external_token_single_space = 7,
  ts_external_token_title_token = 8,
  ts_external_token_todo_token = 9,
  ts_external_token_error_sentinel = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_code_body] = sym_code_body,
  [ts_external_token_html_container_body] = sym_html_container_body,
  [ts_external_token_html_section_body] = sym_html_section_body,
  [ts_external_token_html_token] = sym_html_token,
  [ts_external_token_list_token] = sym_list_token,
  [ts_external_token_p_token] = sym_p_token,
  [ts_external_token_section_dashes] = sym_section_dashes,
  [ts_external_token_single_space] = sym_single_space,
  [ts_external_token_title_token] = sym_title_token,
  [ts_external_token_todo_token] = sym_todo_token,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_code_body] = true,
    [ts_external_token_html_container_body] = true,
    [ts_external_token_html_section_body] = true,
    [ts_external_token_html_token] = true,
    [ts_external_token_list_token] = true,
    [ts_external_token_p_token] = true,
    [ts_external_token_single_space] = true,
    [ts_external_token_title_token] = true,
    [ts_external_token_todo_token] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_section_dashes] = true,
  },
  [3] = {
    [ts_external_token_html_token] = true,
    [ts_external_token_list_token] = true,
    [ts_external_token_p_token] = true,
    [ts_external_token_title_token] = true,
    [ts_external_token_todo_token] = true,
  },
  [4] = {
    [ts_external_token_html_section_body] = true,
  },
  [5] = {
    [ts_external_token_code_body] = true,
  },
  [6] = {
    [ts_external_token_single_space] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_neopolitan_external_scanner_create(void);
void tree_sitter_neopolitan_external_scanner_destroy(void *);
bool tree_sitter_neopolitan_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_neopolitan_external_scanner_serialize(void *, char *);
void tree_sitter_neopolitan_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_neopolitan(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_neopolitan_external_scanner_create,
      tree_sitter_neopolitan_external_scanner_destroy,
      tree_sitter_neopolitan_external_scanner_scan,
      tree_sitter_neopolitan_external_scanner_serialize,
      tree_sitter_neopolitan_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
